# Generated by Django 3.0.6 on 2020-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
