version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 800:800
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/limak_backend/nginx/:/var/log/nginx/
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    environment:
      DJANGO_SETTINGS_MODULE: "limak_backend.settings.production"
    command: >
      sh -c "
        ./manage.py migrate;
        ./manage.py compilemessages;
        ./manage.py collectstatic --noinput;
        gunicorn --bind=0.0.0.0:8000 --timeout=90 --workers=10 --preload limak_backend.wsgi:application;
      "
    volumes:
      - .:/code
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/limak_backend:/var/log/limak_backend
    ports:
      - 45.149.77.38:8787:8000
      - 8000:8000
    env_file:
      - .env
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=limak
      - RABBITMQ_DEFAULT_PASS=covid19

  celery:
    container_name: celery
    build: .
    command: ["celery", "-A", "limak_backend", "worker", "-l", "info", "-E", "--concurrency=10"]
    depends_on:
      - rabbitmq
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/limak_backend:/var/log/limak_backend

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./media/:/media/
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  pgdata:
