# Generated by Django 3.0.6 on 2020-06-12 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothecolor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clothekind',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clothesize',
            name='id',
        ),
        migrations.AddField(
            model_name='clotheinfo',
            name='for_basket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sizes_in_basket', to='store.ClotheSize'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothecolor',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clothekind',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clothesize',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors_in_basket', to='store.ClotheColor'),
        ),
    ]
