# Generated by Django 3.0.6 on 2020-06-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='total_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
