# Generated by Django 3.0.6 on 2020-06-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productinbasket_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
