# Generated by Django 3.0.6 on 2020-06-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200624_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clotheinfo',
            name='for_basket',
        ),
    ]
