# Generated by Django 3.0.7 on 2020-06-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_clotheinfo_for_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.Clothe')),
            ],
        ),
    ]
