# Generated by Django 3.0.6 on 2020-06-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024)),
                ('telephone_number', models.CharField(max_length=64)),
                ('instagram_id', models.CharField(max_length=256)),
                ('telegram_id', models.CharField(max_length=256)),
                ('twitter_id', models.CharField(max_length=256)),
            ],
        ),
    ]
