# Generated by Django 3.0.6 on 2020-06-16 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_basket_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_pay_id', models.CharField(max_length=512, unique=True)),
                ('link', models.CharField(max_length=512)),
                ('amount', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('mail', models.CharField(blank=True, max_length=64, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('errors', models.TextField(default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='store.Basket')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCreatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInquiryResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('id_pay_id', models.CharField(blank=True, max_length=512, null=True)),
                ('order_id', models.CharField(blank=True, max_length=512, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('transaction_inquiry_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage', to='payment.TransactionInquiryResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True, null=True)),
                ('transaction_inquiry_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify', to='payment.TransactionInquiryResponse')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCallback',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'پرداخت انجام نشده است'), (2, 'پرداخت ناموفق بوده است'), (3, 'خطا رخ داده است'), (4, 'بلوکه شده'), (5, 'برگشت به پرداخت کننده'), (6, 'برگشت خورده سیستمی'), (7, 'انصراف از پرداخت'), (8, 'به درگاه پرداخت منتقل شد'), (10, 'در انتظار تایید پرداخت'), (100, 'پرداخت تایید شده است'), (101, 'پرداخت قبلا تایید شده است'), (200, 'به دریافت کننده واریز شد')])),
                ('track_id', models.IntegerField()),
                ('id_pay_id', models.CharField(max_length=512)),
                ('order_id', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('card_no', models.CharField(max_length=128)),
                ('hashed_card_no', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('errors', models.TextField(default='')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='payment.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('transaction_inquiry_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='payment.TransactionInquiryResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyToLoadOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='load', to='store.Basket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('card_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('hashed_card_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('transaction_inquiry_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.TransactionInquiryResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('mail', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.CharField(blank=True, max_length=1024, null=True)),
                ('transaction_inquiry_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='payment.TransactionInquiryResponse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('id_pay_id', 'order'), name='unique_order'),
        ),
    ]
