# Generated by Django 3.0.6 on 2020-06-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_basket_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToLoadOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCallback',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'پرداخت انجام نشده است'), (2, 'پرداخت ناموفق بوده است'), (3, 'خطا رخ داده است'), (4, 'بلوکه شده'), (5, 'برگشت به پرداخت کننده'), (6, 'برگشت خورده سیستمی'), (7, 'انصراف از پرداخت'), (8, 'به درگاه پرداخت منتقل شد'), (10, 'در انتظار تایید پرداخت'), (100, 'پرداخت تایید شده است'), (101, 'پرداخت قبلا تایید شده است'), (200, 'به دریافت کننده واریز شد')])),
                ('track_id', models.IntegerField()),
                ('id_pay_id', models.CharField(max_length=512)),
                ('order_id', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('card_no', models.CharField(max_length=128)),
                ('hashed_card_no', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('errors', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='errors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('id_pay_id', 'order'), name='unique_order'),
        ),
        migrations.AddField(
            model_name='transactioncallback',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='payment.Transaction'),
        ),
        migrations.AddField(
            model_name='readytoloadorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='load', to='store.Basket'),
        ),
        migrations.AddField(
            model_name='readytoloadorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loads', to=settings.AUTH_USER_MODEL),
        ),
    ]
