# Generated by Django 3.0.6 on 2020-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200624_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_pay_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
