# Generated by Django 3.0.7 on 2020-06-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200625_1155'),
        ('payment', '0002_auto_20200622_1814'),
    ]

    operations = [
    ]
